name: jetleaf_logging
description: Flexible and pluggable logging library with ANSI and structured output.
version: 1.0.5

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_logging
issue_tracker: https://github.com/jetleaf/jetleaf_logging/issues
documentation: https://jetleaf.hapnium.com/docs/logging

topics:
  - logging
  - monitoring
  - jetleaf
  - console
  - ansi

keywords:
  - logging
  - monitoring
  - jetleaf
  - ansi
  - logger

environment:
  sdk: ^3.9.0

dependencies:
  jetleaf_lang: ^1.0.5

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0